data<-read.csv("household_power_consumption.txt",sep=";")
subdata<-data[data$Date %in% c("1/2/2007","2/2/2007"),]
date<-(subdata[,1])
time<-(subdata[,2])
x<-paste(date,time)
datetime<-strptime(x,"%d/%m/%Y %H:%M:%S")
sub_metering_1<-as.numeric(paste(subdata[["Sub_metering_1"]]))
sub_metering_2<-as.numeric(paste(subdata$Sub_metering_2))
sub_metering_3<-as.numeric(paste(subdata[["Sub_metering_3"]]))
png("plot3.png", width=480, height=480)
with(subdata,plot(datetime,sub_metering_1,type="lines"))
with(subdata,lines(datetime,sub_metering_2,col="orange"))
with(subdata,lines(datetime,sub_metering_3,col="blue"))
legend("topright", lty = 1, col = c("black","orange", "blue"), legend =c("sub_metering_1", "Sub_metering_2","Sub_metering_3"))
dev.off()
