data<-read.csv("household_power_consumption.txt",sep=";")
subdata<-data[data$Date %in% c("1/2/2007","2/2/2007"),]
date<-(subdata[,1])
time<-(subdata[,2])
x<-paste(date,time)
datetime<-strptime(x,"%d/%m/%Y %H:%M:%S")
global_active_power<-as.numeric(paste(subdata[,3]))
sub_metering_1<-as.numeric(paste(subdata[["Sub_metering_1"]]))
sub_metering_2<-as.numeric(paste(subdata$Sub_metering_2))
sub_metering_3<-as.numeric(paste(subdata[["Sub_metering_3"]]))
Global_reactive_power<-as.numeric(paste(subdata[["Global_reactive_power"]]))
Voltage<-as.numeric(paste(subdata[["Voltage"]]))
png("plot4.png", width=480, height=480)
par(mfrow = c(2, 2))
with(subdata,{
plot(datetime,global_active_power,type="lines",xlab="",ylab="Global Active Power")
plot(datetime,paste(Voltage),type="lines",ylab="Voltage")
plot(datetime,sub_metering_1,type="lines",ylab="Energy sub metering")
lines(datetime,sub_metering_2,col="orange")
lines(datetime,sub_metering_3,col="blue")
plot(datetime,paste(Global_reactive_power),type="lines")})
dev.off()
